### ISSUE TITLE
Choose a websocket technology.

### ISSUE THREAD

**Issue by Mindful-Developer** [gamingbuddhist/Wraiths-CJ9#1]
Must choose technology for the code jam from the approved technologies list: 
https://www.pythondiscord.com/events/code-jams/9/frameworks/

**Comment by bindsdev** [comment]
FastAPI is my top choice. It is very intuitive, powerful, robust, and performant. In addition, it supports type hints and is based off of them. Combined with MyPy tooling and the typing module, we will have a guaranteed type safe environment on our hands.

**Comment by Mindful-Developer** [comment]
I like FastAPI also. I've heard great things about it and think we could make any project we choose work with it.

**Comment by BFragel44** [comment]
FastAPI has my vote - I think this is the best option for the project.

**Comment by Mindful-Developer** [comment]
3 is a majority, so unless someone has any major issues with FastAPI, that is what it's gonna be!
