### ISSUE TITLE
Modify signatures of `ImageFilter` methods

### ISSUE THREAD

**Issue by bindsdev** [gamingbuddhist/Wraiths-CJ9#21]
From the filters that have been implemented, none of them really utilize an instance or set any meaningful instance variables. In addition, some implementations do not even access anything on the instance. Due to this, I propose that we can make the abstract methods also class methods since the current filters are setting *class* variables. This could also be a sign that there might want to be more thought on how to implement this base class.

**Comment by Mindful-Developer** [comment]
Because it's acting on the image that gets passed in directly, there really isn't much need for instance variables in my opinion.

**Comment by bindsdev** [comment]
> Because it's acting on the image that gets passed in directly, there really isn't much need for instance variables in my opinion.

Well yes that is exactly what I am saying. That is why we can modify the signatures and potentially remove `self`

**Comment by Mindful-Developer** [comment]
Yeah. I agree. More of a minor problem at the moment though. Lots of major things to keep pushing through.
